### ISSUE TITLE
Revamp number of iterations vs. number of configs tracking

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#715]
Discussed offline:

- previously (#642) we artificially increased the iteration count so that when we repeated trials it wouldn't lessen the number of configs we sampled
- now that we're separating the optimizer (suggest config) and scheduler (repeat of configs), the we can
  - [x] move the tracking of number of configs suggested to the `suggest()` routine in the Optimizer (#711), and 
  - [x] `number of trials executed` to the Scheduler
- that opens up the door for more flexible stopping conditions (#427)
- to do that, we should also cleanup our terminology and 
  - [x] rename `max_iterations` to `num_config_suggestions`, and 
  - [x] add a new `max_trials` argument (separate PR though I think)

_Originally posted by @bpkroth in https://github.com/microsoft/MLOS/pull/710#discussion_r1526797056_

**Comment by motus** [comment]
I think we've fixed this one in #713 and #719
