### ISSUE TITLE
Expand improved docstrings documentation

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#891]
- [ ] Add documentation tests
- [x] Add general documentation on philosophy and usage #887
- [x] Adjust README documentation links #887 
- [ ] Adds documentation for Environments
  - [ ] Add documentation about `tunable_params` and `tunable_param_maps`
  - [ ] Add documentation about Config variable substitution logic (e.g., `required_args`, `const_args`).
- [ ] Adds documentation for Services
- [ ] Adds documentation for Tunables #890 
- [ ] Adds documentation for Optimizers
